swagger: "2.0"
info:
  version: 0.1.0
  title: Lab Blocks API
  description: An API to support dynamic UI for exploring APIs.
  termsOfService: http://www.kennedylabs.com/terms/
  contact:
    name: Kevin Kennedy
    email: kevin@kennedylabs.com
    url: http://www.kennedylabs.com/
  license:
    name: MIT
    url: http://github.com/kennedylabs/lab-blocks-api/blob/master/LICENSE
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /definitions:
    get:
      description: Gets root definitions
      operationId: getRootDefinitions
      parameters:
        - name: skip
          in: query
          description: number of results to skip
          required: false
          type: integer
          format: int32
        - name: take
          in: query
          description: number of results to take
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: definition response
          schema:
            type: array
            items:
              $ref: '#/definitions/Definition'
        500:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new definiton.
      operationId: addDefintion
      parameters:
        - name: definition
          in: body
          description: definiton to add
          required: true
          schema:
            $ref: '#/definitions/NewDefinition'
      responses:
        200:
          description: definition response
          schema:
            $ref: '#/definitions/Definition'
        500:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /definitions/{identifier}:
    get:
      description: Returns a defintion based on an identifier.
      operationId: findDefinitionByIdentifier
      parameters:
        - name: identifier
          in: path
          description: Indentifier of definition to fetch
          required: true
          type: string
      responses:
        200:
          description: defintion response
          schema:
            $ref: '#/definitions/Definition'
        500:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Deletes a definiton based on the identifier supplied.
      operationId: deleteDefiniton
      parameters:
        - name: identifier
          in: path
          description: Identifier of definition to fetch
          required: true
          type: string
      responses:
        204:
          description: defintion deleted
        500:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Definition:
    allOf:
      - $ref: '#/definitions/NewDefinition'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewDefinition:
    required:
      - name
    properties:
      name:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string